language:
  #Match message language to player language set in client
  auto-language: true
  default-language: "en_us"

# Custom join and leave massages. You can change them in language files
join-leave-messages:
  custom-join-message: true
  custom-leave-message: true