language:
  #Match message language to player language set in client
  auto-language: true
  default-language: "en_us"

# Custom join and leave massages. You can change them in language files
join-leave-messages:
  disable-join: false
  disable-leave: false
  custom-join-message: true
  custom-leave-message: true

chat:
  format-enabled: true
  format: "&f<%nickname%&f> "
  staffchat-enabled: true
  staffchat-format: "&f[&9STAFF&f] &f<%nickname%&f> "

# Storage options: sqlite, mysql
# If you're not sure what to do here, leave both "type" fields at sqlite, plugin will take care of the rest
storage:
  #If you want to sync player data in bungeecord setup set this one separate to server data
  playerdata:
    type: sqlite
    host: localhost
    table: sbasics_players
    database: database
    port: 3306
    username: root
    password: password
    ssl: true
    verifycertificate: true
  # Server specific data like warps and homes that should not be synced in bungeecord setup
  # Remember to change "table" name to a unique name to avoid issues
  serverdata:
    type: sqlite
    host: localhost
    table: sbasics_serverdata
    database: database
    port: 3306
    username: root
    password: password
    ssl: true
    verifycertificate: true