name: ServerBasics
version: ${project.version}
main: eu.endermite.serverbasics.ServerBasics
api-version: 1.13
authors: [ YouHaveTrouble ]
softdepend:
  - PlaceholderAPI
permissions:
  serverbasics.gamemode.survival:
    default: op
  serverbasics.gamemode.creative:
    default: op
  serverbasics.gamemode.adventure:
    default: op
  serverbasics.gamemode.spectator:
    default: op
  serverbasics.chat.color:
    default: op
  serverbasics.command.hat.equip:
    default: op
